const defaultItems = [
  {
    name: 'Basic Sword',
    slot: 'Weapon',
    description: 'Ordinary sword',
    effect: 'Adds strength',
    effect_value: 10,
    price: 300,
    picture: 'https://image.flaticon.com/icons/png/512/1037/1037974.png',
  },
  {
    name: 'Basic Bow',
    slot: 'Weapon',
    description: 'Ordinary bow',
    effect: 'Adds dexterity',
    effect_value: 10,
    price: 300,
    picture: 'https://cdn2.iconfinder.com/data/icons/flat-icons-19/512/Hunting_bow.png',
  },
  {
    name: 'Basic Staff',
    slot: 'Weapon',
    description: 'Ordinary staff',
    effect: 'Adds wisdom',
    effect_value: 10,
    price: 300,
    picture: 'https://image.flaticon.com/icons/png/512/2380/2380051.png',
  },
  {
    name: 'Magic Robe',
    slot: 'Body',
    description: 'Wear it and get rid of even more errors!',
    effect: 'Adds wisdom and health',
    effect_value: 80,
    price: 2000,
    equipped: false,
    picture: 'https://image.flaticon.com/icons/png/512/1255/1255166.png',
  },
  {
    name: 'Heavy Greaves',
    slot: 'Boots',
    description: 'Protection for your foots',
    effect: 'Adds strength and health',
    effect_value: 60,
    price: 1200,
    equipped: false,
    picture: 'https://image.flaticon.com/icons/png/512/1465/1465151.png',
  },
  {
    name: 'Chain Mail',
    slot: 'Body',
    description: 'Protection for your body',
    effect: 'Adds strength and health',
    effect_value: 80,
    price: 2000,
    equipped: false,
    picture: 'https://image.flaticon.com/icons/png/512/2286/2286427.png',
  },
  {
    name: 'Leather Cap',
    slot: 'Head',
    description: 'Protection for your head section',
    effect: 'Adds dexterity and health',
    effect_value: 40,
    price: 800,
    equipped: false,
    picture: 'https://image.flaticon.com/icons/png/512/1391/1391352.png',
  },
];

module.exports = defaultItems;
